{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7597a7b0",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "print(\"Welcome to Game Rental App\")\n",
    "while(1):\n",
    "    print(\"Press: \")\n",
    "    print(\"1. Register as Seller\")\n",
    "    print(\"2. Register as Gamer\")\n",
    "    print(\"3. Login as Seller\")\n",
    "    print(\"4. Login as Gamer\")\n",
    "    print(\"5. Exit\")\n",
    "    in1=int(input())\n",
    "    if in1==1:\n",
    "        print(\"Enter Email ID\")\n",
    "        Email_ID=input()\n",
    "        print(\"Enter Username\")\n",
    "        Username=input()\n",
    "        print(\"Enter Password\")\n",
    "        Password=input()\n",
    "        print(\"Enter Contact Number\")\n",
    "        Contact_Number=input()\n",
    "        try:\n",
    "            f=open('Sellers.json','r')\n",
    "            content=json.load(f)\n",
    "            if Username in str(content):\n",
    "                print(\"Username already exists !!\")\n",
    "                continue\n",
    "        except JSONDecodeError:\n",
    "            pass\n",
    "        if \"@admin.com\" not in Email_ID or (len(Email_ID)*len(Username)*len(Password)*len(Contact_Number))==0 or len(str(Contact_Number))!=10 or len(Password)<=4:\n",
    "            print(\"Please Enter Valid Data !!\")\n",
    "            continue\n",
    "        else:\n",
    "            operations.Register('seller','Gamers.json','Sellers.json',Email_ID,Username,Password,Contact_Number)\n",
    "            print(\"Registered Successully as Seller\")\n",
    "            continue\n",
    "    elif in1==2:\n",
    "        print(\"Enter Email ID\")\n",
    "        Email_ID=input()\n",
    "        print(\"Enter Username\")\n",
    "        Username=input()\n",
    "        print(\"Enter Password\")\n",
    "        Password=input()\n",
    "        print(\"Enter Contact Number\")\n",
    "        Contact_Number=input()\n",
    "        if \".com\" not in Email_ID or (len(Email_ID)*len(Username)*len(Password)*len(Contact_Number))==0 or len(Contact_Number)!=10 or len(Password)<=4:\n",
    "            print(\"Please Enter Valid Data\")\n",
    "            continue\n",
    "        else:\n",
    "            operations.Register('gamer','Gamers.json','Sellers.json',Email_ID,Username,Password,Contact_Number)\n",
    "            print(\"Registered Successully as Gamer\")\n",
    "            continue\n",
    "    elif in1==3:\n",
    "        print(\"Enter Username\")\n",
    "        Username=input()\n",
    "        print(\"Enter Password\")\n",
    "        Password=input()\n",
    "        ch=operations.Login('seller','Gamers.json','Sellers.json',Username,Password)\n",
    "        if ch==True:\n",
    "            f=open('Sellers.json','r')\n",
    "            content=json.load(f)\n",
    "            user_details=[]\n",
    "            for i in range(len(content)):\n",
    "                if content[i][\"Username\"]==Username:\n",
    "                    user_details=content[i]\n",
    "                    break\n",
    "            print(\"Welcome \"+str(Username))\n",
    "            while(1):\n",
    "                print(\"Press: \")\n",
    "                print(\"1. Create Product\")\n",
    "                print(\"2. Update Product\")\n",
    "                print(\"3. View all created Products\")\n",
    "                print(\"4. View Product Details by ID\")\n",
    "                print(\"5. View User Profile\")\n",
    "                print(\"6. Logout\")\n",
    "                in2=int(input())\n",
    "                if in2==1:\n",
    "                    Product_id=operations.AutoGenerate_ProductID()\n",
    "                    print(\"Product ID generated is \"+str(Product_id))\n",
    "                    print(\"Enter Product Name\")\n",
    "                    Product_Name=input()\n",
    "                    print(\"Enter Product Type\")\n",
    "                    Product_type=input()\n",
    "                    print(\"Enter Price per Day\")\n",
    "                    Price_per_day=int(input())\n",
    "                    print(\"Enter Total Stock Available\")\n",
    "                    total_stock=int(input())\n",
    "                    if len(Product_Name)*len(Product_type)==0 or Price_per_day<=0 or total_stock<=0:\n",
    "                        print(\"Please enter valid data !!\")\n",
    "                        continue\n",
    "                    operations.Create_Product(Username,'Products.json',Product_id,Product_Name,Product_type,Price_per_day,total_stock)\n",
    "                    print(\"Product Created Successfully\")\n",
    "                elif in2==2:\n",
    "                    print(\"Enter Product ID\")\n",
    "                    Product_id=input()\n",
    "                    print(\"Enter Detail to be updated(Product Title | Product Type | Price Per Day | Total Stock Available)\")\n",
    "                    Detail_to_be_updated=input()\n",
    "                    print(\"Enter Updated detail\")\n",
    "                    Updated_detail=input()\n",
    "                    ch=operations.Update_Product(Username,'Products.json',Product_id,Detail_to_be_updated,Updated_detail)\n",
    "                    if ch==True:\n",
    "                        print(\"Product updated successfully !!\")\n",
    "                    else:\n",
    "                        print(\"Product not updated !!\")\n",
    "                elif in2==3:\n",
    "                    details=operations.Fetch_all_Products_created_by_seller(Username,'Products.json')\n",
    "                    if len(details)==0:\n",
    "                        print(\"No Products Created !!\")\n",
    "                    else:\n",
    "                        for i in range(len(details)):\n",
    "                            print(\"Product ID: \"+str(details[i][\"Product ID\"]))\n",
    "                            print(\"Product Title: \"+str(details[i][\"Product Title\"]))\n",
    "                            print(\"Product Type: \"+str(details[i][\"Product Type\"]))\n",
    "                            print(\"Price Per Day: \"+str(details[i][\"Price Per Day\"]))\n",
    "                            print(\"Total Stock Available: \"+str(details[i][\"Total Stock Available\"]))\n",
    "                            print('\\n')\n",
    "                elif in2==4:\n",
    "                    print(\"Enter Product ID\")\n",
    "                    Product_Id=input()\n",
    "                    details=operations.Fetch_Product_By_ID('Products.json',Product_Id)\n",
    "                    if len(details)==0:\n",
    "                        print(\"Invalid ID\")\n",
    "                    else:\n",
    "                         for i in range(len(details)):\n",
    "                            print(\"Product Title: \"+str(details[i][\"Product Title\"]))\n",
    "                            print(\"Product Type: \"+str(details[i][\"Product Type\"]))\n",
    "                            print(\"Price Per Day: \"+str(details[i][\"Price Per Day\"]))\n",
    "                            print(\"Total Stock Available: \"+str(details[i][\"Total Stock Available\"]))\n",
    "                            print('\\n')\n",
    "                         continue\n",
    "                elif in2==5:\n",
    "                    print(\"Enter Username\")\n",
    "                    usrnm=input()\n",
    "                    details=operations.View_User_Details('Gamers.json',usrnm)\n",
    "                    if len(details)==0:\n",
    "                        print(\"Invalid Username\")\n",
    "                    else:\n",
    "                        for i in range(len(details)):\n",
    "                            print(\"Email: \"+str(details[i][\"Email\"]))\n",
    "                            print(\"Contact Number: \"+str(details[i][\"Contact Number\"]))\n",
    "                            print(\"Wishlist: \"+str(details[i][\"Wishlist\"]))\n",
    "                            print(\"Cart: \")\n",
    "                            cart=details[i][\"Cart\"]\n",
    "                            for j in range(len(cart)):\n",
    "                                print(\"  Product ID: \"+str(cart[j][\"Product ID\"]))\n",
    "                                print(\"  Quantity: \"+str(cart[j][\"Quantity\"]))\n",
    "                                print(\"  Price Per Day: \"+str(cart[j][\"Price\"]))\n",
    "                                print(\"  Booking Start Date: \"+str(cart[j][\"Booking Start Date\"]))\n",
    "                                print(\"  Booking End Date: \"+str(cart[j][\"Booking End Date\"]))\n",
    "                                print('\\n')\n",
    "                            print('\\n')\n",
    "                        continue\n",
    "                elif in2==6:\n",
    "                    break\n",
    "                else:\n",
    "                    print(\"Please Enter valid input\")\n",
    "        else:\n",
    "            print(\"Invalid Credentials !!\")\n",
    "    elif in1==4:\n",
    "        print(\"Enter Username\")\n",
    "        Username=input()\n",
    "        print(\"Enter Password\")\n",
    "        Password=input()\n",
    "        ch=operations.Login('gamer','Gamers.json','Sellers.json',Username,Password)\n",
    "        if ch==True:\n",
    "            print(\"Welcome \"+str(Username))\n",
    "            in3=1\n",
    "            while(in3!=7):\n",
    "                print(\"Press: \")\n",
    "                print(\"1. View all Product\")\n",
    "                print(\"2. Manage wishlist\")\n",
    "                print(\"3. Manage cart\")\n",
    "                print(\"4. Place order\")\n",
    "                print(\"5. Update Profile\")\n",
    "                print(\"6. View Orders\")\n",
    "                print(\"7. Logout\")\n",
    "                in3=int(input())\n",
    "                if in3==1:\n",
    "                    l=operations.Fetch_all_products('Products.json')\n",
    "                    if len(l)==0:\n",
    "                        print(\"No Products created !!\")\n",
    "                    else:\n",
    "                        for i in range(len(l)):\n",
    "                            print(\"Product ID: \"+str(l[i][\"Product ID\"]))\n",
    "                            print(\"Product Title: \"+str(l[i][\"Product Title\"]))\n",
    "                            print(\"Product Type: \"+str(l[i][\"Product Type\"]))\n",
    "                            print(\"Price Per Day: \"+str(l[i][\"Price Per Day\"]))\n",
    "                            print(\"Total Stock Available: \"+str(l[i][\"Total Stock Available\"]))\n",
    "                            print('\\n')\n",
    "                        continue\n",
    "                elif in3==2:\n",
    "                    print(\"Press: \")\n",
    "                    print(\"1. Add item to wishlist\")\n",
    "                    print(\"2. Remove Item from wishlist\")\n",
    "                    in31=int(input())\n",
    "                    if in31==1:\n",
    "                        print(\"Enter Product ID\")\n",
    "                        Product_Id=input()\n",
    "                        f=open('Products.json','r')\n",
    "                        try:\n",
    "                            content=json.load(f)\n",
    "                        except JSONDecodeError:\n",
    "                            print(\"No products created !!\")\n",
    "                            continue\n",
    "                        if Product_Id not in str(content):\n",
    "                            print(\"Please Enter Valid Product ID\")\n",
    "                            continue\n",
    "                        else:\n",
    "                            ch=operations.Add_item_to_wishlist(Username,Product_Id,'Gamers.json')\n",
    "                            if ch==True:\n",
    "                                print(\"Added item successfully !!\")\n",
    "                                continue\n",
    "                            else:\n",
    "                                print(\"Cannot add item !!\")\n",
    "                                continue\n",
    "                    if in31==2:\n",
    "                        print(\"Enter Product ID\")\n",
    "                        Product_Id=input()\n",
    "                        f=open('Products.json','r')\n",
    "                        try:\n",
    "                            content=json.load(f)\n",
    "                        except JSONDecodeError:\n",
    "                            print(\"No products created !!\")\n",
    "                            continue\n",
    "                        if Product_Id not in str(content):\n",
    "                            print(\"Please Enter Valid Product ID\")\n",
    "                            continue\n",
    "                        else:\n",
    "                            ch=operations.Remove_item_from_wishlist(Username,Product_Id,'Gamers.json')\n",
    "                            if ch==True:\n",
    "                                print(\"Removed item successfully !!\")\n",
    "                                continue\n",
    "                            else:\n",
    "                                print(\"Cannot remove item !!\")\n",
    "                                continue\n",
    "                    else:\n",
    "                        print(\"Please Enter Valid choice\")\n",
    "                elif in3==3:\n",
    "                    print(\"Press: \")\n",
    "                    print(\"1. Add item to cart\")\n",
    "                    print(\"2. Remove Item from cart\")\n",
    "                    print(\"3. View Cart\")\n",
    "                    in31=int(input())\n",
    "                    if in31==1:\n",
    "                        print(\"Enter Product ID\")\n",
    "                        Product_Id=input()\n",
    "                        print(\"Enter Quantity\")\n",
    "                        Quantity=int(input())\n",
    "                        print(\"Enter Booking Start Date (YYYY-MM-DD)\")\n",
    "                        Booking_start_date=input()\n",
    "                        print(\"Enter Booking End Date (YYYY-MM-DD)\")\n",
    "                        Booking_end_date=input()\n",
    "                        f=open('Products.json','r')\n",
    "                        try:\n",
    "                            content=json.load(f)\n",
    "                            f.close()\n",
    "                        except JSONDecodeError:\n",
    "                            print(\"No products created !!\")\n",
    "                            f.close()\n",
    "                            continue\n",
    "                        if Product_Id not in str(content):\n",
    "                            print(\"Please Enter Valid Product ID\")\n",
    "                            continue\n",
    "                        can_add=operations.Add_item_to_cart(Username,Product_Id,Quantity,'Gamers.json',Booking_start_date,Booking_end_date,'Products.json')\n",
    "                        f.close()\n",
    "                        if can_add==True:\n",
    "                            print(\"Added item successfully !!\")\n",
    "                            continue\n",
    "                        else:\n",
    "                            print(\"Cannot add item to cart !!\")\n",
    "                            continue\n",
    "                    if in31==2:\n",
    "                        print(\"Enter Product ID\")\n",
    "                        Product_Id=input()\n",
    "                        f=open('Products.json','r')\n",
    "                        try:\n",
    "                            content=json.load(f)\n",
    "                            f.close()\n",
    "                        except JSONDecodeError:\n",
    "                            print(\"No products created !!\")\n",
    "                            f.close()\n",
    "                            continue\n",
    "                        if Product_Id not in str(content):\n",
    "                            print(\"Please Enter Valid Product ID\")\n",
    "                            continue\n",
    "                        can_remove=operations.Remove_item_from_cart(Username,Product_Id,'Gamers.json')\n",
    "                        if can_remove==True:\n",
    "                            print(\"Item removed successfully from cart !!\")\n",
    "                        else:\n",
    "                            print(\"Cannot remove item\")\n",
    "                    elif in31==3:\n",
    "                        cart=operations.View_Cart(Username,'Gamers.json')\n",
    "                        if len(cart)==0:\n",
    "                            print(\"Cart Empty !!\")\n",
    "                        else:\n",
    "                            for i in range(len(cart)):\n",
    "                                print(\"Product ID: \"+str(cart[i][\"Product ID\"]))\n",
    "                                print(\"Quantity: \"+str(cart[i][\"Quantity\"]))\n",
    "                                print(\"Price Per Day: \"+str(cart[i][\"Price\"]))\n",
    "                                print(\"Booking Start Date: \"+str(cart[i][\"Booking Start Date\"]))\n",
    "                                print(\"Booking End Date: \"+str(cart[i][\"Booking End Date\"]))\n",
    "                                print('\\n')\n",
    "                    else:\n",
    "                        print(\"Please Enter Valid choice\")\n",
    "                elif in3==4:\n",
    "                    Order_id=operations.AutoGenerate_OrderID()\n",
    "                    print(\"Order ID genrated is \"+str(Order_id))\n",
    "                    order_placed=operations.Place_order(Username,'Gamers.json',Order_id,'Orders.json','Products.json')\n",
    "                    if order_placed==True:\n",
    "                        print(\"Order Placed Successfully with Order ID \"+str(Order_id))\n",
    "                    else:\n",
    "                        print(\"Order Unsuccessful !!\")\n",
    "                elif in3==5:\n",
    "                    print(\"Enter Detail to be updated ( Email | Password | Contact Number )\")\n",
    "                    Detail_to_be_updated=input()\n",
    "                    print(\"Enter Updated detail\")\n",
    "                    Updated_detail=input()\n",
    "                    upd=operations.Update_User('Gamers.json',Username,Detail_to_be_updated,Updated_detail)\n",
    "                    if upd==True:\n",
    "                        print(\"Profile Updated successfully !!\")\n",
    "                    else:\n",
    "                        print(\"Cannot Update Profile !!\")\n",
    "                elif in3==6:\n",
    "                    orders=operations.Fetch_all_orders('Orders.json',Username)\n",
    "                    if len(orders)==0:\n",
    "                        print(\"No orders placed !!\")\n",
    "                    else:\n",
    "                        for i in range(len(orders)):\n",
    "                            print(\"Order ID: \"+str(orders[i][\"Order ID\"]))\n",
    "                            print(\"Items: \")\n",
    "                            cart=orders[i][\"Items\"]\n",
    "                            for j in range(len(cart)):\n",
    "                                print(\"  Product ID: \"+str(cart[j][\"Product ID\"]))\n",
    "                                print(\"  Quantity: \"+str(cart[j][\"Quantity\"]))\n",
    "                                print(\"  Price Per Day: \"+str(cart[j][\"Price\"]))\n",
    "                                print(\"  Booking Start Date: \"+str(cart[j][\"Booking Start Date\"]))\n",
    "                                print(\"  Booking End Date: \"+str(cart[j][\"Booking End Date\"]))\n",
    "                                print('\\n')\n",
    "                            print(\"Total Cost: \"+str(orders[i][\"Total Cost\"]))\n",
    "                elif in3==7:\n",
    "                    break\n",
    "                else:\n",
    "                    print(\"Please Enter Valid choice\")\n",
    "        else:\n",
    "            print(\"Invalid Credentials !!\")\n",
    "    elif in1==5:\n",
    "        break\n",
    "    else:\n",
    "        print(\"Please Enter Valid choice\")        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dd3bc93c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
